# Bnuuy Time
# docker-compose.yml
services:
  bnuuy-time:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: bnuuy-time
    restart: unless-stopped
    ports:
      - 127.0.0.1:7891:8000/tcp
